- Cargo.toml
- tests/round_trips.rs
Shifting over the happy path integration test so it is run with `cargo test`. A few auto fmts along the way.
> Move happy path test to integration tests

- src/lib.rs
- src/types.rs
Remove dead key session_keys from the complete handshake struct response. Updated one test, but dropped the rest since the plan is to split off the chacha stuff anyways, let me know if that is a bad idea though.
Wondering if it's worth breaking the mutable packet handler out of the handshake structs, I'll dig into that a bit.
> Remove session keys from complete handshake struct

- Cargo.lock
- Cargo.toml
- src/hkdf.rs
- src/lib.rs
Dropping the `sha2` and `hkdf` dependencies in favor of an internal implementation for HKDF based on RFC5869 and `bitcoin_hashes`. This is limited to BIP324 requirements, so hardcoded with SHA256. The interface is also not as flexible as RFC5869 allows.
> BIP324 HKDF implementation

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/chachapoly.rs
- src/error.rs
- src/hkdf.rs
- src/lib.rs
- src/types.rs
Created a crate feature flag which gates all implementation details which require the standard library. This feature flag is on by default, but follows the standard pattern where it can be disabled with the `default-features` flag. BIP324's own deps have been cleaned up to only pull in std deps when necessary.
Added a new CI check to make sure the library is actually `no_std` compliant. Introduced the `cross` dependency to do this since it was a little flaky locally, hopefully not too much trouble in CI.
The Random Number Generator std dep required some minor interface tweaks where the RNG is passed down implicitly if called from a function that is only built for std.
All allocation dependencies are now explicit, but would need another rev to add another feature flag, e.g. `alloc`, and …
> No standard library (no_std) support

- protocol/src/chacha20poly1305.rs
- protocol/src/chacha20poly1305/chacha20.rs
- protocol/src/chacha20poly1305/poly1305.rs
- protocol/src/hkdf.rs
- protocol/src/lib.rs
Went on a weird rabbit hole with the HKDF PR last week, but one finding was the new guidance for best way to make a library no_std: https://github.com/rust-lang/api-guidelines/commit/a5092f827b98b1be2201c782cf974a1e45073687
It makes sense to me for the flags to be strictly additive instead of some confusing logic to find out if it is enabled or not.
> No std best practice

- protocol/src/chacha20poly1305.rs
- protocol/src/fschacha20poly1305.rs
- protocol/src/lib.rs
- proxy/src/main.rs
This is not robust at all yet, but since core nodes don't appear to send any decoy packets before the version packet, it does work.
> Handshake working on a real life node

- .github/workflows/ci.yml
- Cargo.lock
- protocol/src/chacha20poly1305/chacha20.rs
- protocol/src/lib.rs
Locked the two dependencies which were causing issues building on MSRV of 1.56.1:
```
$ cargo update -p memchr --precise 2.4.1 
$ cargo update -p backtrace --precise 0.3.58
```
This is currently only enforced with the lockfile, not sure how fragile that is.
Closes #49
> Add MSRV build to CI

- protocol/src/lib.rs
- protocol/src/serde.rs
- proxy/Cargo.toml
- proxy/src/bin/async.rs
- proxy/src/bin/v1.rs
- proxy/src/lib.rs
Add v2 message serde leveraging as much of rust-bitcoin's `NetworkMessage` encodings as possible. There is some weirdness here since rust-bitcoin has a `NetworkMessage` as well as a `RawNetworkMessage` wrapper which focuses on the serde. The `RawNetworkMessage` is V1 specific however (e.g. checksums and lengths) which does not play nice with V2. Some of the logic is spread across the structs. `NetworkMessage` is V2 friendly so that is our lingua franca here, but some bespoke code needed to be copied over for now.
> Add v2 serde

- protocol/src/lib.rs
- protocol/tests/regtest.sh
If a user isn't using `ReceivedMessage` then they should be able to access the decoy byte which is a somwhat arbitrary number. Also did some const renaming for clarity
> lib(exports): make useful constants public

- protocol/src/fschacha20poly1305.rs
Using 64 bit counter to match [the official BIP324 spec](https://github.com/bitcoin/bips/blob/master/bip-0324.mediawiki#user-content-Rekeying_wrappers_FSChaCha20Poly1305_and_FSChaCha20). The reference implementation uses a u32 so this probably isn't a big deal, but figure better safe than sorry here.
> Update forward secrecy nonce creation counter

- protocol/src/lib.rs
Each packet handler should be one-to-one with a session ID, so I allow access to a field on the struct here. Resolves #61 
cc @nyonson @Kixunil
> Allow access to `session_id`

- protocol/src/lib.rs
- protocol/tests/round_trips.rs
- proxy/src/bin/proxy.rs
This adds support for receiving (and ignoring) decoy packets in the handshake before the final version packet is sent.
Without this patch, our handshake fails if any decoy packets are sent in the handshake because it currently assumes that only a version packet is sent. This hasn't bitten us yet because Core doesn't send decoys, but it is definitely not meeting the spec. The [spec](https://github.com/bitcoin/bips/blob/master/bip-0324.mediawiki?plain=1#L126) has the specifics on the decoy packets. 
> Encrypted packets have an '''ignore bit''', which makes them '''decoy packets''' if set. Decoy packets are to be ignored by the receiver apart from verifying they decrypt correctly. Either peer may send such decoy packets at any point from here on. These form the primary shapability mechanism …
> Handle decoy packets in handshake

- protocol/src/fschacha20poly1305.rs
- protocol/src/lib.rs
- protocol/tests/round_trips.rs
- proxy/src/bin/proxy.rs
- proxy/src/lib.rs
* Dropping the `ReceivedMessage` struct in favor of the `PacketType` enum and `Payload` struct. 
* This negates the need for https://github.com/rust-bitcoin/bip324/pull/59 and closes #57 
* The heart of the refactor is in `PacketReader::decrypt_contents`, everything kinda bubbles up from there. That is still the spot where I am not quite sure to do with the header byte (which is currently only used to flag decoy packets). The caller probably doesn't care about the header byte, but it is difficult to ask for memory allocation to include it, but then ignore it. Figure most will use the `with_alloc` version though where we wrap it behind the Payload struct, so keeping it simple here for now.
* The PacketHandler functions where greatly simplified after this refactor, so went ahead and just …
> Drop ReceivedMessage and handle sending decoys in handshake

- Cargo.lock
- protocol/Cargo.toml
- protocol/tests/regtest.sh
- protocol/tests/round_trips.rs
regtest.sh was outputting some confusing noise when testing locally, so added a few smarts to the script to clean up the bitcoind instance.
* `regtest.sh` is now entirely responsible for starting and stopping the require bitcoind daemon. The test no longer calls `stop` at the end, it gets to just focus on testing.
* Dropped the rpc dependency since the test no longer needs to call it.
* The `dbg!` macro usage was causing some confusing double output. I believe our use case is better suited by just `println!`.
> Harden regtest script

- Cargo.lock
- protocol/Cargo.toml
- protocol/README.md
- protocol/src/lib.rs
- proxy/Cargo.toml
- proxy/src/bin/proxy.rs
- proxy/src/lib.rs
Add the `AsyncProtocol` wrapper interface for easy protocol setup, sending, and receiving.
* Feature flag gated with the new `async` flag. 
* Example usage in the `proxy` crate. Makes the proxy code super simple.
* We are using [futures-rs](https://github.com/rust-lang/futures-rs) for the general `AsyncRead` and `AsyncWrite` traits to code the wrapper against. The Only annoying thing at the moment is the necessary "compat" util to convert Tokio futures to futures-rs futures in `proxy`, but I am not sure if there is a better way with all the different future traits.
* Tested the proxy update with Nakamoto.
* Moved the `split_garbage` function into the `Handshake` so that it can just implicitly use the remote terminator. Also makes more organizational sense to me.
* Using default …
> Add high level async protocol interface

- proxy/README.md
- proxy/config_spec.toml
- proxy/src/bin/proxy.rs
- proxy/src/bin/v1.rs
- proxy/src/lib.rs
* Allow the proxy to run on bitcoin networks other than mainnet.
* Now that both the V2 and V1 async read options are cancellation safe (by making them little state machines) we can go back to the proxy be a simple select loop.
* Ran with nakamoto locally.
> Add network flag to proxy and refactor back to one loop

- protocol/src/lib.rs
As [specified in the BIP](https://github.com/bitcoin/bips/blob/master/bip-0324.mediawiki#overview-and-design), giving the caller a chance to fallback to V1 protocol if they want when the remote is talkin V1.
> Short circuit if remote is using the V1 protocol

- protocol/src/lib.rs
- proxy/src/lib.rs
The underlying `read_exact` implementations are not cancellation safe themselves, so have to get rid of them and hold onto state manually to ensure no dropped bytes.
Pretty straight forward code change, but I had to do a little deep dive to wrap my head around what was going on: https://blog.yonson.dev/log/2024-10-vol1/
Closes #75
> Improve cancellation safety by switching read_exacts to reads

- Cargo.lock
- proxy/Cargo.toml
- proxy/src/bin/proxy.rs
- proxy/src/bin/v1.rs
- proxy/src/lib.rs
Keeping it simple with the env logger for now, don't have strong opinions on a backend.
Closes #79
> Add logger to proxy app to clean up the noise

- protocol/src/lib.rs
- proxy/src/bin/proxy.rs
* Add a packet size calculator mainly in support of decoy packet allocations in the handshake, but useful in other spots as well.
* Split the 2 failures for garbage bytes.
> Robust packet size calculations and garbage tests

- protocol/src/lib.rs
Extend the protocol's `Io` error variant with some metadata detection so the caller can retry on v1 if they want. Helps implement #27 in the future.
> Add V1 retry detection to error variant

- protocol/Cargo.toml
Checked with `cargo tree -p bip324 -F async --edges features`
> Mark optional deps optional to keep out of dependency tree when not used

- Cargo.lock
- protocol/Cargo.toml
- protocol/src/serde.rs
Small break in the trait bounds on `Decodable` fixed here
> Upgrade `bitcoin` to `0.32.4`

- Cargo.lock
- protocol/Cargo.toml
- protocol/README.md
- protocol/src/lib.rs
- proxy/Cargo.toml
- proxy/src/bin/proxy.rs
Ideally, the `tokio` flag was "additive" with the `async` one, but that would then unnecessarily include the futures dependency.
> Add tokio feature flag for easier integration with the async runtime

- protocol/src/lib.rs
- proxy/src/bin/proxy.rs
Mutable refs appear to fit a little better in the async runtime ecosystem. This interface is a little more flexible since it can always be wrapped by another type which owns the I/O instances and just passes down references.
Since breaking things anyway in the interface, added more descriptive function names.
> Switch to mutable refs for async io

- protocol/src/lib.rs
The high level AsyncProtocol interface attemps to hide all the complexities of using the protocol, including things like cancellation safety. However, some callers might want the simplicity of the protocol handshake while handling the following encoding and decoding operations themselves to squeeze out performance.
> Expose the underlying packet reader/writers

- protocol/src/lib.rs
- protocol/src/serde.rs
> Return unknown short IDs when deserializing

- protocol/src/serde.rs
The underlying IO error might be useful to the caller. Passing it up here. Also `serde` is behind feature `std` so the flag was redundant on `Error`
> Pass source error in `Error`

- Cargo.lock
- protocol/CHANGELOG.md
- protocol/Cargo.toml
> Release v0.6.0 of protocol

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- proxy/Cargo.toml
A few characteristics of how Rust resolves dependencies were at odds in the workspace:
1. Transitive dependency versions are shared across all projects in a workspace. These are set in the workspace's Cargo.lock file.
2. The Rust resolver generally uses the *highest* version of a transitive dependency possible.
3. The `protocol` library project has a more conservative MSRV policy requirement than the `proxy` application.
When introducing the regtest library, I ran into an issue where a new transitive dependency of the `protocol` project was having its version bumped due to it also being in the `proxy` project's dependency tree. This caused the `protocol` project to fail its MSRV policy.
Using `resolver = 3` on rust nightly to set transitive dependency versions in lock file. While setting …
> Use the new v3 resolver for msrv compliant dependency versions

- Cargo.lock
- proxy/Cargo.toml
The path dependency was helpful for testing quick iterations, but switching to a more robust pinned version for stability.
> Pin the proxy protocol crate version

- protocol/Cargo.toml
- protocol/README.md
Allow any compatible Tokio 1.x version to be used with the tokio feature flag, rather than restricting to specific version ranges. This gives users more flexibility to select their preferred Tokio version. But when using the tokio feature with Tokio 1.39.0+, the effective MSRV increases to 1.70.0.
The library only depends on the stable tokio traits `AsyncRead`, `AsyncReadExt`, `AsyncWrite`, `AsyncWriteExt`, so should be compatible with a lot of versions. I'd rather give the caller control in this case, especially since its behind a feature flag, instead of enforcing the strict MSRV requirements of the library.
> Relax tokio version requirements

- justfile
- protocol/README.md
- protocol/benches/cipher_session.rs
- protocol/src/handshake.rs
- protocol/src/lib.rs
- protocol/tests/round_trips.rs
Mostly a shifting of code to allow for some easier refactors of the `Handshake`, but did add the `from_ecdh` method to session materials which I think is a good division of responsibilities.
> Move Handshake to own module

- protocol/Cargo.toml
- protocol/README.md
- protocol/src/io.rs
- protocol/src/lib.rs
- proxy/src/bin/proxy.rs
- proxy/src/lib.rs
Simplifying the protocol crate's interface by dropping the more general futures flag in favor of just the tokio one. All users of the library have been tokio runtime users. If the rust standard library gets its act together and adopts some async I/O interfaces, those will be used in the future instead. Until then, simplifying the interface to explore other things like ffi bindings.
> Remove the futures flag

- README.md
- protocol/Cargo.toml
- protocol/README.md
- protocol/doc/DESIGN.md
- protocol/src/fschacha20poly1305.rs
- protocol/src/io.rs
- protocol/src/lib.rs
- protocol/src/serde.rs
- protocol/tests/round_trips.rs
- proxy/Cargo.toml
Add a std library I/O (aka blocking) high level `Protocol` interface. Also experiments with some new API refactors which could be good for the existing async version.
> Add a std IO protocol interface

- protocol/src/lib.rs
This has no impact on performance, just a more read-able implementation.
> Simplify decrypt packet len function

- protocol/examples/bufreader.rs
Trying to capture just how effective a bufreader is for the BIP-324 protocol. I think this shows that it is usually going to help, probably never hurt.
How it generally looks on my machine:
```
> cargo run --release --example bufreader --features tokio
Finished `release` profile [optimized] target(s) in 0.05s
Running `target/release/examples/bufreader`
Bitcoin Traffic: 100000 total messages, 9940000 bytes
Without BufReader: 126 ms
With BufReader:    98 ms
Improvement:       22.1%
Large Messages: 3000 total messages, 90112000 bytes
Without BufReader: 234 ms
With BufReader:    233 ms
Improvement:       0.1%
Small Messages: 100000 total messages, 300000 bytes
Without BufReader: 101 ms
With BufReader:    72 ms
Improvement:       28.2%
```
> Add bufreader example

- .github/workflows/ci.yml
- justfile
The fmt command doesn't need "--all" with this version of nightly.
> Drop unnecessary cargo flags
